apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
data:
  PORT: "3000"
  DB_HOST: "dbstore.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_NAME: "taskdb"
  DB_SSL: "true"
