apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: dev
type: Opaque
stringData:
  DB_USER: "taskadmin"
  DB_PASSWORD: "ReplaceThis"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: prod
type: Opaque
stringData:
  DB_USER: "taskadmin"
  DB_PASSWORD: "ReplaceThis"
